#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
while(true){
	if(vexRT[Btn7U]){
		motor[port2]=127;
		motor[port3]=127;
		motor[port8]=-127;
		motor[port9]=-127;
	}else if(vexRT[Btn7D]){
		motor[port2]=-127;
		motor[port3]=-127;
		motor[port8]=127;
		motor[port9]=127;
	}else{
		motor[port2]=0;
		motor[port3]=0;
		motor[port8]=0;
		motor[port9]=0;
	}
}
}
