#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		if(vexRT[Btn6U]){
			motor[port2]=64;
			}else if(vexRT[Btn6D]){
			motor[port2]=-64;
			}else{
			motor[port2]=0;
		}
	}
}
