#pragma config(Sensor, dgtl1,  ,               sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
while(true){
	clearDebugStream();
	writeDebugStreamLine("Jumper value %d",SensorValue[dgtl1]);
}
}
