#pragma config(Motor,  port1,           frontLeftWheel, tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           backLeftWheel, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           backRightWheel, tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          frontRightWheel, tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		/*
		motor[frontLeftWheel]=127;
		motor[frontRightWheel]=127;

		motor[backLeftWheel]=127;
		motor[backRightWheel]=127;

		sleep(10000);
		/*/
		motor[port1] = vexRT[Ch3] + vexRT[Ch1];
		motor[port10] = vexRT[Ch3] - vexRT[Ch1];
		//*/

	}
}
