#pragma config(Sensor, dgtl1,  SONARin,        sensorSONAR_cm)
#pragma config(Motor,  port1,           driveLeft,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port5,           arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          driveRight,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main () {
	while(true){
		if(vexRT[Btn7U]){
			motor[port1]=127;
			motor[port10]=127;
			while(SensorValue[SONARin]>35){
				motor[claw]=30;
			}
			motor[claw]=0;
			motor[port1]=64;
			motor[port10]=-64;
			motor[port1]=124
			motor[port10]=124
			sleep(3*1000)
			motor[claw]=0;
			motor[port1]=0;
			motor[port10]=-0;
			motor[port1]=0
			motor[port10]=0
		}
		if(vexRT[Btn8U]){
			motor[arm]=127;
			sleep(1*1000);
			motor[arm]=0;
		}
	}
}
